### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by supposedly** [kamicut/lebanon-maps#1]
Hi!! This was exactly what I needed for an ongoing project of mine, but I'd like to have an outright license to refer to. If the data's entirely yours, would you mind adding a `LICENSE` file to make it clear under what conditions you want these maps to be used? (Otherwise, could you clarify under what terms it was originally published?)

Thanks so much :)

**Comment by kamicut** [comment]
Hey @supposedly, I don't remember if I got these from [GADM](https://gadm.org/download_country_v3.html) or OSM, so I would guess let's use GADM's license:

https://gadm.org/data.html
*The data are freely available for academic use and other non-commercial use. Redistribution, or commercial use is not allowed without prior permission.*

I also modified some of the data, for example Beirut is cut into three districts because it was used for https://lebanonelectiondata.org for 2005, 2009. But this isn't the case for the 2018 elections. If you want more granularity, you can use the GADM level 3 cadaster data and join them up to districts but that's more work.

If you need commercial use you can extract the data from OSM.

**Comment by supposedly** [comment]
Brilliant, TYSM again!
